data:
  channels: 3
  dataset: CIFAR10Pair
  fixed_noise: false
  gaussian_dequantization: false
  image_size: 32
  logit_transform: false
  num_workers: 4
  random_flip: true
  rescaled: true
  uniform_dequantization: false
diffusion:
  beta_end: 0.01
  beta_schedule: const
  beta_start: 0.0001
  num_diffusion_timesteps: 1000
model:
  attn_resolutions:
  - 16
  ch: 128
  ch_mult:
  - 1
  - 2
  - 2
  - 2
  dropout: 0.1
  ema: true
  ema_rate: 0.9999
  in_channels: 6
  num_res_blocks: 2
  out_ch: 3
  resamp_with_conv: true
  type: modified
  var_type: fixedlarge
optim: 
  amsgrad: false
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.0002
  optimizer: Adam
  weight_decay: 0.0
sampling: 
  batch_size: 64
  last_only: true
  #ckpt_id: 600000
training: 
  batch_size: 100
  n_epochs: 10000
  n_iters: 5000000
  snapshot_freq: 10000
  validation_freq: 5000
